"""
Service - RAG Pipeline
========================
Retrieval-Augmented Generation pipeline that combines vector search
(retrieval) with LLM generation to produce grounded answers.
"""

from __future__ import annotations

import logging
from typing import Dict, Generator, List, Optional

from backend.services.embedding_service import embed_text
from backend.services.llm_service import generate_text, stream_response
from backend.services.vector_search import search
from backend.utils.decorators import log_execution
from backend.utils.helpers import truncate_text
from backend.utils.prompts import RAG_ANSWER_PROMPT

logger = logging.getLogger(__name__)


@log_execution
def retrieve_context(
    query: str,
    document_id: Optional[str] = None,
    top_k: int = 5,
) -> str:
    """Retrieve the most relevant text chunks for a query.

    Parameters
    ----------
    query : str
        The user's natural-language question.
    document_id : str, optional
        Restrict retrieval to a single document.
    top_k : int
        Maximum number of chunks to return.

    Returns
    -------
    str
        Concatenated context text from the top-k chunks.
    """
    results = search(query, document_id=document_id, top_k=top_k)

    if not results:
        logger.warning("No relevant chunks found for query: %.60s…", query)
        return ""

    context_parts: List[str] = []
    for idx, (text, score, doc_id) in enumerate(results, 1):
        context_parts.append(f"[Source {idx} | Score: {score:.2f}]\n{text}")

    context = "\n\n---\n\n".join(context_parts)
    logger.info("Retrieved %d chunks (total %d chars) for RAG context", len(results), len(context))
    return context


@log_execution
def generate_answer(query: str, context: str) -> str:
    """Generate an LLM answer grounded in the retrieved context.

    Parameters
    ----------
    query : str
        The user's question.
    context : str
        Retrieved context text.

    Returns
    -------
    str
        The LLM's answer.
    """
    if not context:
        return (
            "I couldn't find relevant information in the uploaded documents "
            "to answer your question. Please try rephrasing or uploading "
            "additional documents."
        )

    prompt = RAG_ANSWER_PROMPT.format(
        context=truncate_text(context, 5000),
        question=query,
    )
    return generate_text(prompt, max_tokens=600)


@log_execution
def full_rag_answer(
    query: str,
    document_id: Optional[str] = None,
    top_k: int = 5,
) -> Dict:
    """End-to-end RAG: retrieve → generate → return answer + sources.

    Returns
    -------
    dict
        Keys: ``answer``, ``sources`` (list of dicts with text / score).
    """
    results = search(query, document_id=document_id, top_k=top_k)

    sources = [
        {"text": text, "score": round(score, 4), "document_id": doc_id}
        for text, score, doc_id in results
    ]

    context = "\n\n---\n\n".join(
        f"[Source {i}]\n{text}" for i, (text, _, _) in enumerate(results, 1)
    )

    answer = generate_answer(query, context)

    return {
        "query": query,
        "answer": answer,
        "sources": sources,
    }


def stream_rag_response(
    query: str,
    document_id: Optional[str] = None,
    top_k: int = 5,
) -> Generator[str, None, None]:
    """Streaming variant of the RAG pipeline.

    Yields tokens as they are generated by the LLM.
    """
    context = retrieve_context(query, document_id=document_id, top_k=top_k)

    if not context:
        yield "I couldn't find relevant information to answer your question."
        return

    prompt = RAG_ANSWER_PROMPT.format(
        context=truncate_text(context, 5000),
        question=query,
    )

    for token in stream_response(prompt):
        yield token
